version: "3.7"

networks:
  net:
    driver: overlay
    attachable: true

volumes:
    prometheus: {}
    grafana: {}
    alertmanager: {}
    loki-data: {}

configs:
  caddy_config:
    file: ./caddy/Caddyfile
  prometheus_test:
    file: ./prometheus/conf/prometheus.yml

services:
  loki:
    #image: zet694/zet694_loki:k23-aee064d
    image: harbor.tgceshi.com/loging/loki:pro-220905
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - loki-data:/data/loki
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == manager
      replicas: 1
    networks:
      - net

  promtail:
    #image: zet694/zet694_promtail:master-7212564
    image: harbor.tgceshi.com/loging/promtail:pro-220905
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /usr/local/nginx/logs:/var/log
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - net

  grafana:
    # image: zet694/zet694_grafana:7.0.4
    image: harbor.tgceshi.com/loging/grafana:9.1.2
    networks:
      - net
    # environment:
    #   - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
    #   - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    #   - GF_USERS_ALLOW_SIGN_UP=false
    env_file:
     - ./grafana/.env
    volumes:
      - grafana:/var/lib/grafana
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  node-exporter:
    image: zet694/zet694_node_exporter:v1.0.1
    networks:
      - net
    environment:
      - TZ=Asia/Shanghai
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  prometheus:
    image: zet694/zet694_prometheus
    environment:
      - TZ=Asia/Shanghai
    networks:
      - net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - prometheus:/prometheus
    configs:
      - source: prometheus_test
        target: /etc/prometheus/prometheus.yml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M

  caddy:
    image: caddy:2.1.0-beta.1-alpine
    ports:
      - "0.0.0.0:3000:3000"
      - "0.0.0.0:9090:9090"
      - "0.0.0.0:3100:3100"
    networks:
      - net
    environment:
#      - ADMIN_USER=${ADMIN_USER:-promo}
#      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-promo}
      #  - ADMIN_USER=admin
      #  - ADMIN_PASSWORD=JDJhJDEwJEVCNmdaNEg2Ti5iejRMYkF3MFZhZ3VtV3E1SzBWZEZ5Q3VWc0tzOEJwZE9TaFlZdEVkZDhX
      - TZ=Asia/Shanghai
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=JDJhJDEwJEo3LmwvZjUzeVFZNDJidEE0ZXJhby40YUoybXMyb2pldUxhLmJpa1BXeG9PVWg1Ry9PS2l5
    configs:
      - source: caddy_config
        target: /etc/caddy/Caddyfile
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M